version: "1"
services:
  db:
    image: postgres
    ports:
      - "5432:${pgPort}"
    environment:
      - POSTGRES_PASSWORD=${pgPassword}
      - POSTGRES_DB=${pgDatabase}
      - POSTGRES_USER=${pgUSer}
    volumes:
      - data:/data/db
  api:
    container_name: api-devops
    restart: on-failure
    build: ./apiNode
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/src/app
    env_file:
      - .env
  react:
    container_name: react-devops
    restart: always
    build: ./react-app
    ports:
      - "3000:3000"

volumes:
  data: {}
